# Generated by Django 2.2.12 on 2020-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
